name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: "25"
      - uses: DeLaGuardo/setup-clojure@13.7.0
        with:
          cli: latest
          bb: latest
      - uses: actions/cache@v6
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          key: deps-${{ hashFiles('deps.edn', 'bb.edn') }}
      - run: bb ci
      - run: bb examples
